AWSTemplateFormatVersion: "2010-09-09"

Description: -<
    ...

Transform: [ "AWS::Serverless-2016-10-31" ]

Globals:
    Function:
        Runtime: "nodejs14.x"
        MemorySize: 128
        Timeout: 30
        Environment:
            Variables:
                AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "Organization", "Environment", "Lambda", "List-Secrets", "Secret-Service" ] ]
            Description: "..."
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            CodeUri: "."
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        Path: /api/list-secrets
                        Method: GET
